package com.fednow.iso20022.domain.common;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

/**
 * Payment Identification - Identifiers for tracking payments through the system.
 *
 * Contains various IDs used to track payments from initiation through settlement:
 * - Instruction ID: Bank's internal reference
 * - End-to-End ID: Customer's reference (preserved throughout chain)
 * - Transaction ID: Interbank transaction reference
 * - UETR: Universal unique identifier for cross-border/instant payments
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentIdentification {

    /**
     * Instruction Identification - Unique identifier assigned by the instructing party
     * to identify the instruction.
     * Max 35 characters.
     */
    @Size(max = 35, message = "Instruction ID must not exceed 35 characters")
    private String instructionId;

    /**
     * End-to-End Identification - Unique identifier assigned by the initiating party
     * that is passed on throughout the entire payment chain.
     * MANDATORY for FedNow payments.
     * Max 35 characters.
     */
    @NotBlank(message = "End-to-End ID is required")
    @Size(max = 35, message = "End-to-End ID must not exceed 35 characters")
    private String endToEndId;

    /**
     * Transaction Identification - Unique identifier assigned by the first instructing agent
     * to identify the transaction. Used for interbank transactions.
     * Max 35 characters.
     */
    @Size(max = 35, message = "Transaction ID must not exceed 35 characters")
    private String transactionId;

    /**
     * Unique End-to-End Transaction Reference (UETR) - Universally unique identifier
     * to provide end-to-end tracking of a payment transaction.
     *
     * For FedNow, this is generated by the sending bank and is a UUID v4.
     * It remains unchanged throughout the entire payment chain.
     */
    private UUID uetr;

    /**
     * Clearing System Reference - Reference assigned by the clearing system.
     * For FedNow, this is assigned by the FedNow system itself.
     * Max 35 characters.
     */
    @Size(max = 35, message = "Clearing System Reference must not exceed 35 characters")
    private String clearingSystemReference;
}
