package com.fednow.iso20022.converter.utils;

import com.fasterxml.uuid.Generators;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Utility class for generating unique identifiers for ISO 20022 messages.
 *
 * Generates:
 * - Message IDs (max 35 characters)
 * - Transaction IDs (max 35 characters)
 * - UETRs (UUID v4)
 * - Clearing system references
 */
@Component
public class IdGenerator {

    private static final DateTimeFormatter MESSAGE_ID_FORMATTER = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
    private static final AtomicLong messageSequence = new AtomicLong(0);
    private static final AtomicLong transactionSequence = new AtomicLong(0);

    /**
     * Generates a unique message ID.
     *
     * Format: {prefix}-{timestamp}-{sequence}
     * Example: "BANK-FDW-20240115103045-001"
     *
     * @param prefix prefix for the message ID (e.g., "BANK-FDW", "CUST")
     * @return unique message ID (max 35 characters)
     */
    public String generateMessageId(String prefix) {
        String timestamp = LocalDateTime.now().format(MESSAGE_ID_FORMATTER);
        long sequence = messageSequence.incrementAndGet() % 10000; // Reset at 10000
        String messageId = String.format("%s-%s-%04d", prefix, timestamp, sequence);

        // Ensure it doesn't exceed 35 characters
        if (messageId.length() > 35) {
            messageId = messageId.substring(0, 35);
        }

        return messageId;
    }

    /**
     * Generates a unique message ID for bank-to-FedNow messages.
     *
     * @return message ID for pacs.008 and similar
     */
    public String generateBankMessageId() {
        return generateMessageId("BANK-FDW");
    }

    /**
     * Generates a unique message ID for customer-facing messages.
     *
     * @return message ID for pain.002 and similar
     */
    public String generateCustomerMessageId() {
        return generateMessageId("CUST-STS");
    }

    /**
     * Generates a unique message ID for status reports.
     *
     * @return message ID for pacs.002 and similar
     */
    public String generateStatusMessageId() {
        return generateMessageId("STS");
    }

    /**
     * Generates a unique message ID for returns/reversals.
     *
     * @return message ID for pacs.004, pain.007
     */
    public String generateReturnMessageId() {
        return generateMessageId("RTN");
    }

    /**
     * Generates a unique message ID for notifications.
     *
     * @return message ID for camt.054
     */
    public String generateNotificationMessageId() {
        return generateMessageId("NTF");
    }

    /**
     * Generates a unique message ID for system events.
     *
     * @return message ID for admi.002
     */
    public String generateSystemEventMessageId() {
        return generateMessageId("EVT");
    }

    /**
     * Generates a unique transaction ID.
     *
     * Format: TXN-{timestamp}-{sequence}
     * Example: "TXN-20240115103045-0001"
     *
     * @return unique transaction ID (max 35 characters)
     */
    public String generateTransactionId() {
        String timestamp = LocalDateTime.now().format(MESSAGE_ID_FORMATTER);
        long sequence = transactionSequence.incrementAndGet() % 100000; // Reset at 100000
        return String.format("TXN-%s-%05d", timestamp, sequence);
    }

    /**
     * Generates a unique instruction ID.
     *
     * Format: INST-{timestamp}-{sequence}
     * Example: "INST-20240115103045-0001"
     *
     * @return unique instruction ID (max 35 characters)
     */
    public String generateInstructionId() {
        String timestamp = LocalDateTime.now().format(MESSAGE_ID_FORMATTER);
        long sequence = transactionSequence.incrementAndGet() % 100000;
        return String.format("INST-%s-%05d", timestamp, sequence);
    }

    /**
     * Generates a UETR (Unique End-to-End Transaction Reference).
     *
     * Uses UUID v4 (random) as specified by ISO 20022.
     *
     * @return UUID v4 for UETR
     */
    public UUID generateUetr() {
        return Generators.randomBasedGenerator().generate();
    }

    /**
     * Generates a clearing system reference.
     *
     * This would typically be generated by the clearing system (FedNow),
     * but for simulation/testing purposes we generate it.
     *
     * Format: FDW-CLR-{timestamp}-{sequence}
     * Example: "FDW-CLR-20240115-123456"
     *
     * @return clearing system reference (max 35 characters)
     */
    public String generateClearingSystemReference() {
        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd"));
        long sequence = transactionSequence.get() % 1000000; // 6 digits
        return String.format("FDW-CLR-%s-%06d", date, sequence);
    }

    /**
     * Generates an account servicer reference.
     *
     * This is the bank's internal reference for a transaction.
     *
     * Format: ASR-{timestamp}-{sequence}
     * Example: "ASR-20240115103045-12345"
     *
     * @return account servicer reference (max 35 characters)
     */
    public String generateAccountServicerReference() {
        String timestamp = LocalDateTime.now().format(MESSAGE_ID_FORMATTER);
        long sequence = transactionSequence.get() % 100000;
        return String.format("ASR-%s-%05d", timestamp, sequence);
    }

    /**
     * Generates a status identification.
     *
     * Used for status entries in pain.002 and pacs.002.
     *
     * Format: STSID-{sequence}
     * Example: "STSID-00001"
     *
     * @return status identification (max 35 characters)
     */
    public String generateStatusId() {
        long sequence = transactionSequence.incrementAndGet() % 100000;
        return String.format("STSID-%05d", sequence);
    }

    /**
     * Generates a return/reversal identification.
     *
     * Format: RET-{timestamp}-{sequence}
     * Example: "RET-20240115103045-0001"
     *
     * @return return ID (max 35 characters)
     */
    public String generateReturnId() {
        String timestamp = LocalDateTime.now().format(MESSAGE_ID_FORMATTER);
        long sequence = transactionSequence.incrementAndGet() % 10000;
        return String.format("RET-%s-%04d", timestamp, sequence);
    }

    /**
     * Generates a notification/entry reference.
     *
     * Used for entries in camt.054.
     *
     * Format: ENT-{timestamp}-{sequence}
     * Example: "ENT-20240115103045-001"
     *
     * @return entry reference (max 35 characters)
     */
    public String generateEntryReference() {
        String timestamp = LocalDateTime.now().format(MESSAGE_ID_FORMATTER);
        long sequence = transactionSequence.incrementAndGet() % 10000;
        return String.format("ENT-%s-%04d", timestamp, sequence);
    }

    /**
     * Generates a batch identification.
     *
     * Format: BATCH-{timestamp}
     * Example: "BATCH-20240115103045"
     *
     * @return batch ID (max 35 characters)
     */
    public String generateBatchId() {
        String timestamp = LocalDateTime.now().format(MESSAGE_ID_FORMATTER);
        return String.format("BATCH-%s", timestamp);
    }

    /**
     * Resets all sequence counters.
     * Used primarily for testing.
     */
    public void resetSequences() {
        messageSequence.set(0);
        transactionSequence.set(0);
    }
}
